In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
file=pd.read_csv("creditcard.csv")

In [3]:
file.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [4]:
file.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.918649e-15,5.682686e-16,-8.761736e-15,2.811118e-15,-1.552103e-15,2.040130e-15,-1.698953e-15,-1.893285e-16,-3.147640e-15,...,1.473120e-16,8.042109e-16,5.282512e-16,4.456271e-15,1.426896e-15,1.701640e-15,-3.662252e-16,-1.217809e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [5]:
file.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
file['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [7]:
normal=file[file.Class==0]

In [8]:
fraud=file[file.Class==1]

In [9]:
print(normal.shape)

(284315, 31)

In [10]:
print(normal.shape)

(284315, 31)

In [11]:
normal.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [13]:
file.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [14]:
normal_sample=normal.sample(n=492)

In [15]:
new_file=pd.concat([normal_sample,fraud],axis=0)

In [16]:
new_file.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279982,169225.0,-1.363844,1.461390,-0.473816,-1.712188,1.457624,-0.550586,1.146353,-0.623059,-1.298533,...,0.968415,0.138698,-0.638642,0.344408,1.407943,0.259742,-0.134510,-0.095299,14.72,0
88374,62111.0,-1.000347,1.315898,1.647753,-0.224555,0.053102,-0.565206,1.080321,-0.374338,0.433353,...,-0.380236,-0.427298,0.011421,0.372972,-0.201876,0.038261,0.278208,-0.127641,22.47,0
135609,81326.0,1.141230,0.127321,0.467399,0.978175,-0.247759,-0.048703,-0.199611,0.148109,-0.021800,...,0.237698,0.725324,-0.136731,0.032424,0.596094,-0.194331,0.034006,0.007914,6.41,0
230661,146430.0,1.905450,0.339597,-2.336301,1.409033,0.988191,-0.649758,0.612306,-0.190364,-0.116962,...,0.038052,0.180182,-0.032636,0.578659,0.425127,-0.545864,-0.013734,-0.025209,48.51,0
260484,159578.0,-1.100255,-1.157273,1.381378,-2.973825,0.566609,-0.756826,-0.550952,0.061874,-2.554126,...,-0.069952,-0.084737,-0.314628,-0.562206,0.782788,-0.106855,-0.011629,0.045835,10.00,0
121935,76374.0,-1.570988,0.552861,-0.759188,-2.769435,0.669070,3.332304,-1.899282,2.196357,-1.389906,...,0.602890,0.993013,-0.129926,1.038001,-0.132898,-0.277142,-0.467312,-0.077882,14.00,0
252506,155839.0,0.089906,1.014179,-0.322277,-0.641468,0.980340,-0.494030,0.878015,0.033470,-0.373055,...,-0.273119,-0.645521,0.095022,0.611730,-0.470585,0.091144,0.225097,0.075511,0.89,0
109831,71558.0,-0.467378,1.570531,0.216645,0.767336,0.425485,-0.880933,1.114456,-0.347975,0.134233,...,0.043872,0.761590,0.073520,0.410458,-0.693201,-0.421496,0.609728,0.194270,1.51,0
158747,111703.0,0.170019,1.675535,-2.752452,-0.171903,1.465600,-1.579994,1.112442,0.116319,-0.402585,...,0.019983,0.188645,-0.080560,0.404407,-0.246052,0.545076,0.113904,0.052378,0.76,0
89477,62593.0,1.212495,0.138275,0.461058,0.579846,-0.530701,-0.817637,-0.058510,-0.071769,-0.134489,...,0.102210,0.289609,-0.058107,0.569731,0.451915,0.400541,-0.041137,0.001738,2.02,0

In [17]:
new_file['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [18]:
new_file.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96849.595528,0.026557,0.094966,0.007026,0.040087,-0.002767,0.030909,-0.058982,0.040438,-0.054637,...,0.000375,0.025890,0.035052,0.004443,-0.003598,-0.011525,0.017701,-0.013300,0.028361,77.758455
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [19]:
X=new_file.drop(columns='Class',axis=1)

In [20]:
Y=new_file['Class']

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [22]:
model=LogisticRegression(max_iter=100)

In [23]:
model.fit(X_train,Y_train)

LogisticRegression()

In [24]:
X_train_prediction=model.predict(X_train)

In [25]:
training_data_acuracy=accuracy_score(X_train_prediction,Y_train)*100

In [26]:
print(f"Training Data Accuracy: {training_data_acuracy}%")

Training Data Accuracy: 92.12198221092758%

In [27]:
X_test_prediction=model.predict(X_test)

In [28]:
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)*100

In [29]:
print(f"Test Data Accuracy: {test_data_accuracy}%")

Test Data Accuracy: 92.38578680203045%